name: Deploy Lambda

on:
  push:
    branches:
      - main  # deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Zip Lambda package
        run: zip -r lambda-package.zip . -x "*.git*" "*.github*" "node_modules/aws-sdk/**"

      # 🪣 Upload the zip file to S3
      - name: Upload to S3
        run: |
          aws s3 cp lambda-package.zip s3://vivasayiai-lambda-deployment/lambda-builds/lambda-package.zip \
            --region ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 🚀 Deploy to Lambda using S3 source
      - name: Deploy to AWS Lambda (via S3)
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: tnFarmingAssistant
          s3_bucket: vivasayiai-lambda-deployment
          s3_key: lambda-builds/lambda-package.zip
